CREATE TABLE person(
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(100) NOT NULL UNIQUE,
        birth_year int NOT NULL
);

CREATE TABLE book(
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title varchar(100) NOT NULL,
        author_name varchar(100) NOT NULL,
        publish_year int NOT NULL,
        issuance_time timestamp,
        person_id int REFERENCES person(id) ON DELETE SET NULL
);
